spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  logging:
    level:
      root: INFO
  app:
    cors:
      allowed-origins: ${SPRING_APP_CORS_ALLOWED_ORIGINS}
    jwt:
      secret: ${JWT_SECRET:dev-default-secret}
      expiration: ${JWT_EXPIRATION:86400000}
